# Generated by Django 2.2.14 on 2020-07-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_item_discount_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('A', 'Animals'), ('Edu', 'Education'), ('Env', 'Environment'), ('H', 'Health'), ('HS', 'Human Services'), ('ACH', 'Arts, Culture, and Humanities')], max_length=2),
        ),
    ]
