# Generated by Django 2.2.14 on 2020-07-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200715_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='label',
        ),
        migrations.AddField(
            model_name='item',
            name='organization',
            field=models.TextField(null=True),
        ),
    ]
