# Generated by Django 2.2.14 on 2020-07-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200716_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='org_logo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
