# Generated by Django 2.2.14 on 2020-07-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(blank=True, choices=[('animals', 'Animals'), ('education', 'Education'), ('enviornment', 'Environment'), ('health', 'Health'), ('human-service', 'Human Services'), ('humanitites', 'Arts, Culture, and Humanities')], max_length=15, null=True),
        ),
    ]
