# Generated by Django 2.2.14 on 2020-07-19 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200718_0836'),
        ('core', '0012_auto_20200718_1211'),
    ]

    operations = [
    ]
